= Ateliers socio-artistiques
:page-aliases: .:page/programme/93/ateliers-socioartistiques.html

== ATELIER ÉCRITURE ET LECTURE

En partenariat avec les associations bruxelloises, l’atelier HISTOIRES DE VIES propose aux participantes divers outils d’écriture afin d’explorer leur imaginaire ainsi que leur histoire familiale et intime. L’objectif pour chacune est alors de trouver le fil de son récit personnel à partir de ses souvenirs et de son vécu, afin de pouvoir se raconter à d’autres et de transmettre cet héritage à ses enfants.

[NOTE]
====
* Responsable de l'atelier : Zineb Mouhssin
* Adultes
* Contact pour inscription et info : istudio@istudio.name
* Prix : 150€ de participation aux frais pour les associations partenaires
* Horaires 2021-22 : vendredi matin (10h-13h)
====

== ATELIER TEXTILE DESIGN

SEQUI NATURAM est un atelier basé sur les motifs dans le règne animal et végétal. L’aspect symbolique et liturgique des représentations animales et végétales dans l’art sera revisité par les participants de l’atelier pour donner naissance à des motifs inédits qui seront déclinés sur différents supports textiles et papiers.

Des accessoires simples seront créés ou customisés. Notamment des masques de protection. Une attention particulière sera accordée aux théories scientifiques sur l’origine des pandémies de façon à proposer des créations citoyennes, socialement et écologiquement engagées.

Les masques quitteront alors leur côté fonctionnel pour devenir ornements ou parures. L’objectif de l’atelier est de guider le participant vers un mode d’expression artistique contemporain en résonance avec les enjeux écologiques actuels. L’apprentissage de la création textile est un moyen d’expression pour tout un chacun, initié ou non initié, jeune ou vieux…Le participant sera amené à développer son potentiel créatif par la valorisation de son savoir et de sa culture. L’histoire d’un tissu, le processus de fabrication, la thématique abordée sont autant d’éléments qui permettent d’aller à la rencontre de l’autre et de favoriser l’échange des pratiques et des connaissances. Ce cycle, intitulé SEQUI NATURAM, propose de découvrir des pratiques populaires ancestrales pour teindre nos tissus et vêtements à partir de plantes tinctoriales et ainsi nous reconnecter à la terre dans une logique d'autoproduction et de respect de l'environnement en réintégrant des savoir-faire oubliés où l'écologie tient un rôle central.

[NOTE]
====
* Responsable de l'atelier : Christine Mawet
* Adultes
* Contact pour inscription et info : istudio@istudio.name
* Prix : 100€ de participation aux frais
*  Horaires 2021-22 : mercredi matin (10h-13h) et mercredi après-midi (13h-17h)
====

== ATELIER VIDEO / MONTAGE / IMAGE / SON

IStudio vous propose VOISINAGE, un atelier de création audiovisuelle autour de la thématique du « Vivre-Ensemble ». Composé d’un groupe de participants « réalisateurs » et de participants « interviewés/filmés », l’atelier a pour objectif la réalisation d’un ensemble de court-métrages documentaires sur diverses thématiques en lien avec le « Vivre-Ensemble ».

[NOTE]
====
* Responsable de l'atelier : Enzo Tibi
* Adultes
* Contact pour inscription et info : istudio@istudio.name
* Prix : 30€ de participation aux frais
* Horaires à partir de 2021-2022 : lundi, mercredi et vendredi (17h-20h) si en présentiel ; si en virtuel, selon disponibilité.
====

== ATELIER D'ÉCRITURE

L’atelier d’écriture « Write-Club Digital » est un atelier destiné à un public adulte mixte francophone qui désire apprendre ou se perfectionner dans l’art d’écrire toutes sortes de fictions (roman, nouvelle, théâtre, poème, etc.). Sa particularité est d’avoir lieu en ligne via un service de visio-conférence de type Zoom, qui permet à plusieurs personnes d’être connectées en même temps et ce depuis plusieurs endroits différents.

[NOTE]
====
* Responsable de l'atelier : Gérald Berche-Ngô
* Adultes
* Contact pour inscription et info : istudio@istudio.name
* Prix : 30€ de participation aux frais
* Horaires à partir de 2021-2022 : jeudi (17h-20h) si en présentiel ; si en virtuel, selon disponibilité.
====

== ATELIER PHOTO / VIDEO / STOPMOTION

Dans un monde où le virtuel occupe une place de plus en plus importante, IStudio présente FIGUR’IN, un atelier socio-artistique d’initiation à la mise en scène d’éléments miniatures photo/vidéo/stop motion. FIGUR’IN propose à chacun de ses participants et ses partenaires associatifs de créer un personnage à partir d’une figurine de leur choix afin de le mettre en scène dans une séquence animée.

[NOTE]
====
* Responsable de l'atelier : Safa-Eddine Taghian
* Jeunes & adultes
* Contact pour inscription et info : istudio@istudio.name
* Prix : 150€ de participation aux frais
* Horaires à partir de 2021-2022 : selon disponibilité des associations
==== 

== ATELIER MONTAGE SON / INTERVIEW / ENREGISTREMENT

Collecte de récits de vie

Initiation au techniques radiophoniques, journalistiques et montage son. L'atelier sera composé de trois phases : la préparation de l'interview (réflexion autour des personnages et de l'histoire à raconter, introduction aux techniques radiophoniques, etc.), l'interview et la post-production (traitement de la matière sonore sur un logiciel spécifique, montage, mixage, diffusion en ligne) mais aussi une phase photomontage et écriture.

[NOTE]
====
* Responsable de l’atelier : équipe IStudio & Elora Andrzejewski
* Adultes francophones (mixte)
* Contact pour inscription et info : istudio@istudio.name
* Prix : 20€
* Horaires à partir de 2021- 2022 : week-end selon la disponibilité des participants
====
