= Diffusion
:page-aliases: .:page/root/actu/programme/66/diffusion.html

== DIFFUSION (2020)

=== LES FILIATIONS

Suite à l’atelier de design textile du même nom, le vernissage de l’exposition MOTIFS NOMADES : LES FILIATIONS a eu lieu le dimanche 1er mars 2020 au Musée La Fonderie. Les familles des participants étaient présentes pour découvrir cette mise à l’honneur de leurs ancêtres. Un rassemblement très émouvant qui s’est déroulé dans la joie et la fierté des participants, satisfaits d’avoir accompli un bel ouvrage pour leurs proches et pour le vivre ensemble.
L’exposition avec sa double thématique, la migration des motifs et la filiation, a soulevé au sein de l’atelier une réflexion citoyenne sur les origines de ces migrations. Derrière le voyage des motifs textiles se cachent des migrations humaines, des déplacements de populations. Le participant n’a pu faire l’impasse de ces éléments, le motif permettant d’aller à la rencontre de mouvements géopolitiques, religieux, ou économiques, etc.
Le finissage prévu le dimanche 5 avril a été postposé au dimanche 28 juin en raison de la crise du Covid19. Cette exposition qui devait initialement durer 5 semaines aura finalement été ouverte au public durant 8 semaines. Un beau succès d’estime comme en témoignent les nombreux retours des spectateurs et de l’équipe du Musée. Tant et si bien qu’une demande du Musée a été faite pour conserver une trace de l’exposition dans son Musée permanent.


=== VIVRE ENSEMBLE, MAIS PAS DE TROP PRÈS

Le projet a fait suite à l’atelier VIVRE ENSEMBLE, MAIS PAS DE TROP PRÈS ayant mené à la réalisation d’un documentaire citoyen par des bruxellois initiés par l’animateur aux outils audiovisuels. Le jeudi 15 octobre 2020, l’ensemble des courts-métrages a été présenté au sein des locaux d’IStudio, réunissant pour l’occasion les participants de l’atelier ainsi que des participants d’autres ateliers, projets et activités de l’association.


== DIFFUSION (2019)

=== ART ENSEMBLE OF BRUSSELS

Créations plastiques, musicales et sonores exposées dans le cadre du festival « Next Generation, Please ! » (édition 2018-2019) organisé par BOZAR, le 9 mai 2019.
Les jeunes de l’asbl Calame ont eu l’occasion de présenter le résultat du travail plastique et sonore réalisé dans le cadre de l’atelier d’IStudio. Au cours des séances, ils ont en effet été amenés à composer des affiches basées sur les slogans de mai 68, puis, grâce à un dispositif technique, à traduire ces productions en sons. Pour le festival, l’installation a permis de mettre en avant la relation entre création plastique et création sonore, et s’est présentée elle-même comme une œuvre d’art numérique et interactive mise à disposition des visiteurs.

=== ATELIER CONTE "DE A à Z"

Lecture publique à la Foire du Livre de Tour & Taxis, le 14 Février 2019.
Suite à l’atelier conte « De A à Z » proposé par IStudio, les femmes du cours d’alpha de l’asbl Calame ainsi que les participantes de la Maison des Femmes de Molenbeek (MOVE asbl), ont offert au public la lecture des contes qu’elles avaient choisis et travaillés ensemble. Chaque volontaire a ainsi eu l’opportunité de partager avec les spectateurs le suspense et l’émotion de ces récits, mais aussi de témoigner de l’assurance acquise tout au long de l’atelier. Les femmes ont également pu présenter les livrets illustrés et reliés par leurs soins sur base de ces contes.

 

== DIFFUSION (2018)

=== AMOUR GÂCHÉ

Chanson et clip vidéo présentée dans le cadre du festival « Orfeo & Majnoun », organisé par le Théâtre de la Monnaie, le 30 juin 2018.
Produite au cours de l’atelier d’IStudio organisé avec les jeunes du Foyer de Molenbeek, cette chanson fait partie d’une série de compositions, écrites et enregistrées par le groupe. Les jeunes l’ont sélectionnée parmi l’ensemble pour en réaliser le clip vidéo. Ce dernier, basé sur la technique des ombres chinoises, a ensuite été présenté par les participants lors du festival. A cette occasion, ils ont également pu interpréter la chanson en direct. 

=== AGORA DES IDÉES

Installation plastique et sonore présentée dans le cadre de l’exposition interactive « Next Generation, Please ! » (édition 2017-2018), organisée par BOZAR le 9 mai 2018.
Ce projet est le résultat de l’atelier du même nom, proposé par IStudio et le Centre Culturel Omar Khayyam aux élèves du Collège la Fraternité. Les jeunes ont eu l’occasion de s’initier à la prise de son en rue (via l’exercice du « micro-trottoir ») ainsi qu’à la création plastique, en expérimentant la technique du Patchwork. L’objectif était ainsi d’interroger ensemble des enjeux citoyens actuels, comme l’Europe ou les frontières. Une structure en bois a ensuite été réalisée afin d’accueillir à la fois les compositions des participants, sur les panneaux extérieurs, et le son récolté, à l’intérieur même de l’installation. Les visiteurs étaient alors invités à se déplacer dans cette « Agora des Idées ».

 

== DIFFUSION (2017)

=== WRITE-CLUB

Lecture publique WRITE CLUB le 19 décembre 2017.

=== MOTIFS NOMADES

Exposition « MOTIFS NOMADES » à la Boutique Culturelle le 13 décembre 2017
Avec comme point de départ la migration des motifs, cette exposition est le résultat d'un an d'initiation à la création textile pour les participants de l'atelier couture de l'asbl Cactus et ceux de l'atelier design textile d'IStudio. En écho à cette belle rencontre : de multiples créations dont une œuvre commune en origami, avec une multitude de bateaux, d'oiseaux et de motifs cachés dans le creux des plis, un voyage poétique tout en pudeur où une création sonore vient habiller ou dévoiler une part d'intimité des créateurs.

=== BILAD AL FANN

Diffusion lors de 3 événements du court métrage documentaire « BILAD AL FANN // PAYS DE L'ART », réalisé dans le cadre du projet « Voix d'Ici, voies d'Ailleurs » (VIVA), présentant une série de portraits d'artistes réfugiés réalisé par un groupe de bruxellois sensibilisés et initiés à différentes disciplines telles que le journalisme citoyen, l'approche interculturelle, la création vidéo et sonore.
- Le 11 mars 2017 à la Fonderie, pour la « Museum Night Fever » en partenariat avec Refugees Got Talent asbl
- Le 28 mars 2017 à Inspiring Culture, dans le cadre du colloque européen « 6th ENCATC Academy on Culture in External Relations » sur la thématique « The question of culture in Europe's refugee crisis »
- Le 14 mai 2017 à la Boutique Culturelle asbl dans le cadre du festival « TEKITOI »

=== VOIX D'ICI, VOIES D'AILLEURS

Également diffusé sur le web via une page Soundcloud, Voix d'Ici, Voies d'Ailleurs est un projet dans lequel un groupe de jeunes bruxellois « donne le micro » à des migrants, des primo-arrivants ou des réfugiés vivant à Bruxelles depuis plusieurs années ou parfois seulement quelques mois. Leurs récits, commentaires, débats, etc., sont enregistrés puis mis en valeur grâce à un travail de créations sonores originales. Ces rencontres sont des occasions d'échanger sur les différentes identités culturelles et parcours migratoires des uns et des autres.

== DIFFUSION (2016)

Diffusion du travail effectué dans deux projets (Contes et rencontres et Voies d'ici, Voix d'ailleurs) via deux pages Soundcloud. Contes et Rencontres est un projet qui s'intègre dans le cadre d'activités créatives, socio-artistiques et formatives pour ce qui est de l'apprentissage de la langue française, puisqu'il s'agit d'apprendre à maîtriser le texte en faisant non seulement une analyse du contenu du conte mais aussi de sa structure et d'en dominer la narration et la déclamation. La langue est donc appréhendée sous toutes ses facettes : lecture, expression écrite et expression orale. Après avoir décrypté les textes, les participantes ont été emmenées à réciter ces histoires et à collaborer à la création d'un univers sonore autour de chaque récit.
Dans le projet Voix d'ici, voies d'ailleurs, un groupe de jeunes bruxellois "donne le micro" à des migrants, des primo-arrivants ou des réfugiés vivant à Bruxelles, depuis plusieurs années ou parfois seulement quelques mois. Leurs récits, commentaires, débats, etc., sont enregistrés puis mis en valeur grâce à un travail de créations sonores originales. Ces rencontres sont des occasions d'échanger sur les différentes identités culturelles et parcours migratoires des uns et des autres.


== DIFFUSION (2015)

Production d’un support CD, finalité des ateliers « Il était une fois » et « L’Alphabet de la Sagesse » en partenariat avec l'asbl Cactus. Lors de ces ateliers autour de l’apprentissage de la langue française, les participantes, encadrées par une équipe technique d’artistes formateurs, ont enregistré une compilation de contes récités et mis en scène par elles-mêmes. La diffusion de l'outil audio sur des ondes radio ainsi que sa mise à disposition et sa diffusion dans les associations demandeuses sert également l'apprentissage de la langue française pour d'autres publics tout en y créant d'autres débats autour des thématiques abordées par les contes. Ce projet est destiné principalement à un public migrant et/ou primo-arrivant installé à Bruxelles.

Production et réalisation d’une capsule documentaire d’une durée de dix minutes rendant compte des séances « café philosophique » en partenariat avec l’asbl Maison de quartier Heyvaert de Molenbeek.

Durant la période de janvier à décembre 2015 a eu lieu un projet collectif d’écriture autour des récits de vie d'un groupe de migrants à Bruxelles, intitulé Histoire(s) de vie. Ce projet s’est réalisé en associant publics francophone et non francophone. Un exemple de témoignage est écoutable ici.

== DIFFUSION (2014)

=== DIFFUSION DU FILM TOI(S) ET MOI(S) SUR LA TOILE (2014)

La diffusion du film Toi(s) et moi (s) sur la toile, réalisé en collaboration avec les artistes de IStudio et les élèves du Collège Roi Baudouin, a eu lieu le 10 janvier 2014 dans les locaux de cette école.
Ce film est le résultat d'un projet traitant des nouvelles technologies (internet, réseaux sociaux, etc.), de leur impact sur la société et sur les jeunes. Les réflexions ont débuté par un débat avec notre partenaire Prospective Jeunesse. Ensuite ont été travaillé l'écriture du scénario, le jeu d'acteur et les techniques vidéo, aboutissant à la réalisation de ce film surprenant.

== DIFFUSION (2013)

=== RÉALISATION DU SPECTACLE PAROLES DU CORPS IMAGINAIRE (2013)

Le spectacle Paroles du corps imaginaire (mise en scène d'Inbal Yalon) est axé sur la présentation d'une série de monologues et de chansons issus du répertoire moderne. La première partie du spectacle s'appuie sur une succession de solos féminins. Elle est suivie d'une présentation qui réunit l'ensemble des comédiennes en une lecture-conférence dressant un portrait tragicomique et virulent du monde contemporain.

Spectacle présenté en juin 2013 au Bukta Baktop à Bruxelles.

 

=== RÉALISATION DU SITE HYPERFICTION (2013)

HYPERFICTION est une œuvre littéraire numérique et collective créée lors du « Write Club », l’atelier d’écriture de G. Berche-Ngô. Elle est constituée de micro-nouvelles – ou blitz-fictions – toutes reliées entre elles selon le principe du système hypertexte utilisé sur le web : chaque blitz-fiction contient donc un hypermot, sur lequel il faut clicker pour accéder à la suivante ; chaque hypermot est une clef, un trope, une poésie qui transporte le lecteur d’une histoire à une autre, ou dans la même histoire mais à un moment différent, ou dans une histoire différente mais avec les mêmes personnages, etc. Tout hypertexte étant par nature potentiellement infini, il s’agit ici d’un work-in-progress. D’autres micro-nouvelles viendront au fur et à mesure s’y ajouter, pour faire de l’œuvre un ensemble arborescent, fragmenté et multi-directionnel, un Jardin aux sentiers qui bifurquent.

== DIFFUSION (2012)

=== ÉDITION DU CATALOGUE ANIMAL/ANIMUS (2012)

Catalogue d'un projet de réalisation plastique en 3 dimensions, reposant sur 2 univers plastiques singuliers : les cabinets de curiosités et les Kapalas tibétains. La première collection s'est achevée en janvier 2011.

Photo : Châu Dang ; Texte : G. Berche-Ngô


=== ÉDITION DU LIVRET PÉDAGOGIQUE EMPREINTE (2012)

Composés par les participants non-francophones de l'atelier intitulé Le français dans tous ses états, les textes de cette création sont le résultat de réflexions et de recherches autour des thèmes de l'animalité, de la trace et du rêve.

Photo : Châu Dang


=== RÉALISATION DU PROJET EMPREINTE ET MÉTAMORPHOSE (2012)

Jeu d'acteurs à partir des textes écrits par les apprenants non-francophones lors d'un atelier de théâtre et d'expression française, réalisé en mars 2012 au centre culturel Nekkersdal et en mai 2012 à IStudio.
