= Historique de IStudio ASBL
:navtitle: Historique
:keywords: IStudio, ASBL, Historique
:page-aliases: .:page/root/pr-eacutesentation/9/historique.html

IStudio / IS asbl, anciennement Idéal Stand Art, est une Association Sans But Lucratif fondée en 1979.

Après la création du Stalker, lieu qui accueillera une multitude de spectacles de danse et de théâtre, une nouvelle impulsion est donnée et, dès 1994, l'association met en place des ateliers d'initiation artistique pour les habitants des quartiers bruxellois. Destinés à transmettre aux participants les bases d'une pratique dans des disciplines telles que le théâtre, la danse contemporaine, la peinture, la scénographie, la création de costumes, le maquillage de spectacle, etc., ces ateliers ont également une vocation sociale : il s'agit d’organiser et de développer avec les artistes une plateforme utile à la création de contacts et d'échanges durables entre les habitants bruxellois (sans distinction de culture, âge, milieu social, etc.) et les réseaux socio-culturels et artistiques de la ville. 

En 1997, IStudio / IS asbl obtient la reconnaissance de la Fédération Wallonie-Bruxelles en tant que Centre d'Expression et de Créativité. Cette même année, l'association met en place sa structure permanente, Lézards en tête, destinée à accueillir et soutenir dans ses projets tout public désireux de participer à la vie socio-artistique des quartiers urbains.

En 2004, l'association emménage dans ses nouveaux locaux du 11 boulevard Barthélémy, dans un quartier favorisant la mixité culturelle en plein centre de Bruxelles, et Lézards en tête devient l'actuel IStudio.

Entre 2000 et 2008, IStudio / IS asbl produit et coordonne plusieurs projets pour l'organisation de la parade Zinneke.

En 2011, dans le cadre du nouveau Quinquennat du secteur Cohésion sociale, IStudio ajoute un nouveau projet à ses actions : Le français dans tous ses états (formation FLE accompagnée d’ateliers théâtraux). 

Depuis 2012, IStudio propose également des formations autour de disciplines telles que le design textile, les arts plastiques, le théâtre, la vidéo et le langage cinématographique.

Depuis 2015, l'atelier Voix d'Ici, Voies d'Ailleurs (atelier citoyen et créatif de captation son et image autour des parcours de vie des habitants bruxellois mais aussi des réfugiés et des migrants) est mis en place.

En 2019, IStudio / IS asbl obtient la reconnaissance de la catégorie 4 des Centres d'expression et de créativité de la Fédération Wallonie-Bruxelles.

À ce jour, IStudio / IS asbl a produit des dizaines de spectacles de théâtre et de danse, d'expositions, de films, d'installations plastiques et scénographiques contemporaines, de débats et de conférences.
