= Projet annuel
:page-aliases: .:page/root/actu/programme/62/projet-annuel.html

== VOIX D'ICI, VOIES D'AILLEURS

Le projet Voix d’Ici, Voies d’Ailleurs est intégré au secteur Cohésion sociale dans le cadre du Quinquennat 2016-2020 (prolongé jusqu'à fin 2022). Ce projet citoyen et créatif vise à mettre en relation des publics divers (mixtes, moins mixtes et primo arrivant) qui vivent à Bruxelles.

Certains d’entre eux raconteront leur parcours de vie aux autres et travailleront ensemble sur ces récits pour finalement réaliser une production audio et/ou audio-visuelle qui va ensuite être diffusée sur les ondes radio, dans les associations demandeuses et dans des structures culturelles bruxelloises reconnues.

Ces diffusions seront accompagnées de plates-formes d’échange et de débat public.

[NOTE]
====
* Contact pour inscription et info (prix, horaires) : istudio@istudio.name 
* Adultes
* Non francophones et francophones
====

[IMPORTANT]
====
* Les inscriptions ne seront validées qu'après paiement sur le compte d'IStudio n° 210-0209620-55 avec la communication : nom de l'atelier + nom & prénom du participant
* Aucun remboursement, partiel ou intégral, n'est prévu en cas de désistement
* Dans certains cas, des prix adaptés pourraient être proposés aux participants (chômeurs, CPAS ou étudiants). À voir avec la direction, n'hésitez pas à nous con
====
