= Conditions d'utilisation
:page-aliases: .:terms

Toute utilisation du site web d'IStudio / IS asbl implique l’acceptation préalable des présentes conditions d’utilisation. Votre accès au site d'IStudio / IS asbl est soumis aux conditions d’utilisation et aux lois en vigueur.

== Contenu

Toute information fournie sur ce site l’est exclusivement à titre indicatif et n’est pas juridiquement contraignante. 

L’information fournie sur ce site est aussi complète que possible. IStudio / IS asbl n’assume aucune responsabilité quant à l'exactitude, à l'actualité et au caractère exhaustif des informations qui y sont fournies. Le site et toutes les informations contenues sont disponibles en l'état, sans aucune autre garantie, d'aucune sorte, explicite ou implicite.

En outre, IStudio / IS asbl se réserve le droit de procéder, à tout moment et sans préavis, à des modifications de services, de prix et de règlements.

== Droits d’auteur, propriété industrielle et intellectuelle

Tous les éléments visuels, illustrations, contenus, marques, logos, marques déposées, mentions de service et autres données sont protégées par des droits d’auteur et des droits de propriété intellectuelle. Toute forme de transmission, reproduction, diffusion, publication, adaptation, expédition de tout ou partie du présent site web et de son contenu ou toute utilisation de ceux-ci à des fins commerciales est interdit sans l’autorisation écrite préalable d'IStudio / IS asbl, sauf pour être visionné.

== Droit à l'image

Les photographies publiées sur le site le sont au titre d’illustration des informations seulement. Elles ne peuvent être copiées, exploitées, téléchargées, vendues ou exploitées de toute autre manière. Toute personne reconnaissable représentée sur l’une ou plusieurs photographies diffusées sur le site web d’IStudio / IS asbl peut solliciter le retrait des photographies concernées en adressant un e-mail à IStudio / IS asbl. Le retrait des photographies concernées indemnisera intégralement tout préjudice que prétendrait avoir subi la personne représentée, qui ne pourra solliciter le paiement d’aucun dommages et intérêts complémentaires.

== Respect de la vie privée

Les traitements de données à caractère personnel relatifs à ce site sont soumis à la loi du 8 décembre 1992 relative à la protection de la vie privée à l'égard des traitements de données à caractère personnel. Les informations et données collectées ne sont ni cédées, ni transmises à aucune autre organisation. Toutefois, nous nous réservons le droit de divulguer des informations ou données à caractère personnel sur requête d'une autorité légale en conformité des lois et réglementations en vigueur.

== Hyperliens

Les hyperliens menant du présent site web vers des sites web externes sont conçus pour faciliter l’utilisation du site par ses visiteurs. Cependant, IStudio / IS asbl ne garantit en aucune façon le caractère précis, complet et véridique des informations contenues dans de tels liens hypertexte ou dans d’autres sites Internet. Les risques inhérents à la visite de tels sites liés sont entièrement supportés par l’utilisateur. Leur présence ne signifie en aucune manière qu'IStudio / IS asbl adhère à leur contenu ou accepte une responsabilité quelconque pour le contenu ou l'utilisation de cet autre site web.

== Dommages

IStudio / IS asbl ne peut être tenu responsable d’éventuels dommages directs, indirects ou fortuits résultant de l’utilisation du présent site web. Ceci vaut entre autres pour les éventuelles dommages causés par les infections par virus informatiques ou résultant de votre confiance en des informations fournies sur ce site. 

== Révisions

IStudio / IS asbl peut en tout temps modifier les présentes conditions au moyen d’une mise à jour de cet article. Vous devrez par conséquent revoir les modalités et conditions chaque fois que vous visitez ce site.
