---
content:
  sources:
    - branches: HEAD
      edit_url: "https://github.com/IStudio-ASBL/IStudio-ASBL.github.io/edit/main/{path}"
      url: ./
output:
  destinations:
    - clean: true
      path: build/site
      provider: fs
runtime:
  cache_dir: ./.cache/antora
site:
  robots: allow
  title: IStudio ASBL
  url: https://new.istudio.name
ui:
  bundle:
    snapshot: true
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
urls:
  redirect_facility: netlify
